IF OBJECT_ID('AUDIT_LOGS') IS NULL
BEGIN
    CREATE TABLE [DBO].[AUDIT_LOGS] (
        [ID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
        [TABLE_NAME] NVARCHAR(100) NOT NULL,
        [EVENT_TYPE] NVARCHAR(100) NOT NULL,
        [USER_NAME] NVARCHAR(100) NULL,
        [DATA] NVARCHAR(MAX) NOT NULL,
        [CREATED_AT] DATETIME2 NOT NULL
    );
END
