IF OBJECT_ID('BOOKS') IS NULL
BEGIN
    CREATE TABLE [DBO].[BOOKS] (
        [ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        [NAME] NVARCHAR(200) NOT NULL,
        [AUTHOR] NVARCHAR(150) NOT NULL,
        [SUMMARY] NVARCHAR(1000) NOT NULL,
        [ACTIVE] BIT NOT NULL,
        [CREATED_AT] DATETIME2 NOT NULL,
        CONSTRAINT UQ_BOOK_NAME UNIQUE ([NAME])
    );
END