IF OBJECT_ID('LOGINS') IS NULL
BEGIN
    CREATE TABLE [DBO].[LOGINS] (
        [ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        [USER_NAME] NVARCHAR(MAX) NOT NULL,
        [EMAIL] NVARCHAR(30) NOT NULL,
        [PASSWORD_HASH] NVARCHAR(60) NOT NULL,
        [ROLE] INT NOT NULL,
        [ACTIVE] BIT NOT NULL,
        [CREATED_AT] DATETIME2 NOT NULL,
        CONSTRAINT UQ_LOGIN_EMAIL UNIQUE ([EMAIL]),        
        CONSTRAINT UQ_LOGIN_USER_NAME UNIQUE ([EMAIL])
    );
END