INSERT INTO [DBO].[BOOKS] (ID, NAME, AUTHOR, SUMMARY, ACTIVE, CREATED_AT)
VALUES
  (NEWID(), 'O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 'Uma história poética sobre amizade, amor e lições de vida através dos olhos de uma criança.', 1, SYSDATETIME()),
  (NEWID(), 'Dom Quixote', 'Miguel de Cervantes', 'A clássica aventura de Dom Quixote e seu fiel escudeiro Sancho Pança, explorando idealismo e realidade.', 1, SYSDATETIME()),
  (NEWID(), '1984', 'George Orwell', 'Uma distopia que retrata uma sociedade totalitária e vigilância extrema, abordando liberdade e controle.', 1, SYSDATETIME()),
  (NEWID(), 'O Senhor dos Anéis', 'J.R.R. Tolkien', 'A jornada épica pela Terra-média, com heróis, anéis mágicos e batalhas entre o bem e o mal.', 1, SYSDATETIME()),
  (NEWID(), 'Harry Potter e a Pedra Filosofal', 'J.K. Rowling', 'O início das aventuras de Harry Potter na escola de magia de Hogwarts.', 1, SYSDATETIME()),
  (NEWID(), 'A Revolução dos Bichos', 'George Orwell', 'Uma fábula política sobre animais que se rebelam contra seus donos, crítica ao totalitarismo.', 1, SYSDATETIME()),
  (NEWID(), 'O Alquimista', 'Paulo Coelho', 'Uma fábula sobre seguir sonhos e encontrar o propósito de vida, repleta de ensinamentos espirituais.', 1, SYSDATETIME()),
  (NEWID(), 'A Menina que Roubava Livros', 'Markus Zusak', 'A história de uma garota que encontra consolo nos livros durante os horrores da Segunda Guerra Mundial.', 1, SYSDATETIME()),
  (NEWID(), 'Cem Anos de Solidão', 'Gabriel García Márquez', 'A saga da família Buendía na cidade fictícia de Macondo, com realismo mágico e histórias entrelaçadas.', 1, SYSDATETIME()),
  (NEWID(), 'O Hobbit', 'J.R.R. Tolkien', 'As aventuras de Bilbo Bolseiro em sua jornada para ajudar os anões a recuperar seu tesouro.', 1, SYSDATETIME()),
  (NEWID(), 'O Código Da Vinci', 'Dan Brown', 'Um thriller envolvendo mistérios históricos, símbolos e conspirações.', 1, SYSDATETIME()),
  (NEWID(), 'Anjos e Demônios', 'Dan Brown', 'Robert Langdon investiga uma conspiração dentro da Igreja Católica.', 1, SYSDATETIME()),
  (NEWID(), 'Inferno', 'Dan Brown', 'Uma corrida contra o tempo baseada na obra de Dante Alighieri.', 1, SYSDATETIME()),
  (NEWID(), 'O Símbolo Perdido', 'Dan Brown', 'Segredos escondidos na capital dos EUA envolvendo maçonaria e ciência.', 1, SYSDATETIME()),
  (NEWID(), 'Moby Dick', 'Herman Melville', 'A obsessiva caçada do capitão Ahab à baleia branca.', 1, SYSDATETIME()),
  (NEWID(), 'Orgulho e Preconceito', 'Jane Austen', 'Romance clássico sobre amor, orgulho e questões sociais na Inglaterra do século XIX.', 1, SYSDATETIME()),
  (NEWID(), 'Emma', 'Jane Austen', 'Uma jovem rica tenta combinar casamentos ao seu redor, com consequências inesperadas.', 1, SYSDATETIME()),
  (NEWID(), 'O Morro dos Ventos Uivantes', 'Emily Brontë', 'Uma história intensa de amor e vingança entre famílias na Inglaterra rural.', 1, SYSDATETIME()),
  (NEWID(), 'Jane Eyre', 'Charlotte Brontë', 'A trajetória de uma órfã que enfrenta desafios e encontra o amor verdadeiro.', 1, SYSDATETIME()),
  (NEWID(), 'O Grande Gatsby', 'F. Scott Fitzgerald', 'O romance sobre riqueza, amor e tragédia na década de 1920.', 1, SYSDATETIME()),
  (NEWID(), 'A Metamorfose', 'Franz Kafka', 'A história de Gregor Samsa que acorda transformado em um inseto gigante.', 1, SYSDATETIME()),
  (NEWID(), 'O Processo', 'Franz Kafka', 'Um homem é preso e julgado sem saber o motivo, crítica à burocracia e sociedade.', 1, SYSDATETIME()),
  (NEWID(), 'Crime e Castigo', 'Fiódor Dostoiévski', 'Um jovem comete um crime e enfrenta dilemas morais e psicológicos.', 1, SYSDATETIME());